<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.gbif</groupId>
        <artifactId>dwc-dp-analyser</artifactId>
        <version>0.0.13</version>
    </parent>

    <artifactId>dwc-dp-analyser-cli</artifactId>

    <dependencies>
      <dependency>
          <groupId>org.gbif</groupId>
          <artifactId>dwc-dp-analyser-lib</artifactId>
          <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.gbif</groupId>
        <artifactId>dwc-dp-analyser-api</artifactId>
      </dependency>
      <dependency>
        <groupId>org.gbif</groupId>
        <artifactId>dwc-dp-descriptor</artifactId>
      </dependency>
      <dependency>
        <groupId>org.gbif</groupId>
        <artifactId>dwc-dp-validator-api</artifactId>
      </dependency>

      <!-- Third-party dependencies -->
      <dependency>
          <groupId>info.picocli</groupId>
          <artifactId>picocli</artifactId>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
      </dependency>
      <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
      </dependency>

      <!-- Logging dependencies -->
      <dependency>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-api</artifactId>
      </dependency>

      <!-- Test dependencies -->
      <dependency>
          <groupId>org.junit.jupiter</groupId>
          <artifactId>junit-jupiter</artifactId>
          <scope>test</scope>
      </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <shadedClassifierName>runner</shadedClassifierName>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.gbif.dp.cli.ValidationCli</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
